services:
  mongodb:
    image: mongo:5.0.8
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456admin

  api:
    build: .
    container_name: api-flask
    ports:
      - "5000:5000"
    restart: always
    environment:
      - FLASK_ENV=development
      - MONGODB_DB=users
      - MONGODB_HOST=mongodb
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=123456admin
    depends_on:
      - mongodb
    volumes:
      - ./application:/app/application