replicaCount: 2

appPort: 5000

image: 
  registry: 837255538576.dkr.ecr.us-east-1.amazonaws.com/flask-api
  tag: latest

environmentVariables:
  - name: FLASK_ENV
    value: development
  # - name: FLASK_ENV
  #   value: production

environmentVariablesFrom:
  - secretRef:
      name: mongodb-credentials


livenessProbe:
  httpGet:
    path: /health
    port: 5000
readinessProbe:
  httpGet:
    path: /health
    port: 5000

resources:
  limits:
    cpu: 400m
    memory: 500Mi
  requests:
    cpu: 200m
    memory: 250Mi

ingress:
  enabled: true

mongo:
  database: AgAjA6+6bUoMAwpePBhTx7L3+hd4GcUSGHplfUPf3bxSj/bIs7ZWbwizpGIZYPAC/ygvdmDreqLq3TnCXPiwCNAAbqVHZVzdXEnv6zm1xX66vrmO6NA8Fp54VvRU1MvbrfTAZa6li6ZsF3pqPJmBcfOn2h4Oad+1hId8HoQ25AzAn7RmMId0fku/s0pHe5Y752D2hMjzcNClwtVdhQJ2D6OZVRFUGkkhqD0yIFDxHLvAvRvvavhVBUNSPnl9HN+hKKExnkz1vaybObhEW3zrX3Q5OPk+gBjNxPwd49mR1Y8SsQLCNXCVUsIG0nGzTg0nUsjlN2aVRQk0NiwJzwCffyWOm6eyUgfam43IyZ//yk+BHI+YNV1JO38hYebJhYv2RCXfHjHPMHNV23NcTqWni2iVy8pIvCDrgf6Ga9CI4IF2jJcrQ6mJ0tI68O0jmMPZXdGsS6CY+jraH4HIKSCWCQEJnC0HDGgplIrVzXOXi0kWk4IPp1KgJbMqtPcQAoB/DGoePSBS52yQ60v8Uypx84Z6V5JMN4f7eRKxM4CAqCRTuBVnR3AaY9eI1jCuH0C8ImD2q73o+PRC3fSQyGc4EATcLRxLfHnJBBOFK2ML4vdfBpX+Oy+hLC5oHEbV92JxRTk1BeFRCj1sgtKI8Dnb7wvOFkNRoFS8Hsi5C5sJyLPnF40AO30aTZqW4gYf2BVOTbGDugI6
  host: AgBoRTq5g83CuLS1bOYQ9+dVJfF6/0W5/+0jf3C/B/2PNY8ThtLCJzLZo3h1A8nOA4E06dDylMAiMBhqYVGacjAaT5Bbt/JM5kzkQ84lsV/RE4Mg0r5HuAGAm9vlToNSu7Nol4ts2hxZNIimBO3+1NZcFkAcsNVe2DrHzX8bMqlFT2TBwHCj54YGLFgXOjBedUEZR41iEHwcneDst4IG8c1rS3KckKTcuDCf6HHXRe9cHOO7ZwzQwqTBV59xGsEUXi0Z1o3xgxZQgKcdgbTRofih7iArA2PGVJINAXZpU+IzWRHGwLTveLal+EtKo+SCqnfVTAJtBewOTlYKM/eOgQy+6C0h/3RkbVdpP0gYshOWL78U63Y1iVvvkUnDb0mhysFCUDYZh0O4ddTg05bYhSOkEDzF1QidMd9RdgqhzHsDUgeraKTlh2W+ck4T53/9bhy/1XOTO4/UL8ZLlC5CQBZFNdi7qzXxDS+RLhJjI1KSTiivEqXKCAAgc9CRQ0gVdD9olTWXzCm3u4Z6qzgY8nmOpAyH2RW7Bn27azcL/vlfqHUNVNG9QQ3a6C3URS6S0zvus3fSLNntUzP7CdlfrLEHhDeXVRinP97RZdkK3JwS6VsSSD38G4EbU5sybC33w1ZONG78SR4DqeOyZk2gh9IKIcBSazqUKMR+ts/mDtWpy8J6zVBcxldJdgSpAE0QNIWZhpMH2s63
  password: AgCCDHKW44lOGq+HktVkNUHhgZ/Ji32QnK7EftJBMxE0JhiLoO36n1lDqQgCsK22mLV/ty7oj/aKkBK9QzBZ4Eodf3oTfRVfAN/spy9eGT/0N/bDxnHmujMo3JAEMEFMrjHGwg14SWtjmZe/2xuwF+057CeVHof7+dBoRauj6niYY2tBCQ3R+mWNno9hrYkiN4ZArdrySKxQoE3px+01GDCR99ag6oUbGKlP6WrH5K9+86OUf8hGj5fff2pXRjBZmIa5vCPHm6uz8F5GEYXNMp/BDPIATUQs/0VLg1seY/OoBwe+5NSCU8U/MOneVyOLEBoj0BPfDq+L0tWR29vjBvw1MXq3kzWbrZRdefxfcIhmPtdgDb9GE+Lfu4CfKpDdllK1NqBjWICQ9gP1lFRn5afvJXZGsI6QZmzN/KKKdIF0jbrX/ean9UBDosIU/VRnedMPotVpVN2UGVIsD6KAUauIAwNLP9xeTZakIebjdf6bpxpZTn/hSntwGjND73SYJydsDkdh8he1Ql5evG0SWE7myKfABsvHLjxTU/6M+KqM8Ne1KVS1eMLiuwtL/dpkD5AtCI32wz3llcvyNVCsaK0yL8tFLzgCtS6227qydDTf6Ij19TSLbl6kkaX+EUw8n+dqD8qdfXD8drzKUClq5p/BNqHk7Omywwj0fM8il2zN4E9rvuX9pwSrTrR36q7EgYWt3y+j
  username: AgAIWAsrQp2LkxpyaF70Xsmht8uuBXD2FxUScl5V8RRKk32quNAYogYarT9Ja3rYLzBel/4O1dDxmZ0fei1uCXHmwimem/wGDjRY0SUwQGwf8LotkhbtDUvDHkncS/KCZF+DRK0zrtGkmp5v45KNFDeyBJjH70fKJ8OTLGzf8XYPKHZqn/CmefRRr89fV5NXwjbBsdOJRHnQm5zPrFrfJwPGL78fksGAHBCmh0QkWF0jQbBFfFqPXC+oj6Pn4aIEVmiVlb/uAxGHLGBwQ8HyQBYSzewzIqAPaoR7WaJpSdL+l/kMgPMawmy0HfkCbCk1SIOoZJwHpJpBRAtMsbFjESDquaNduP/hwTbrvpB34LBcGpqQJVIPYtiN9vE9cckISaIaC7Uz41oVBpSNlSdaQBEjJ89FtM7HsVrN9lxI870EJBVb4yPtealPik/VDNsFombq/Q8+yNnO92Cfbp2quOhS1w6bEjtOi7Unx6dh0gOj240SKq0v3QFPM3C3Zb/6TkJrRy/WozRrou3wRVXS3UlHyXi+N7/UldPXyGaU/clK0MxOaigPxcnuha30yjMUSY79/LhXwohMSYzMXPFsPb4ruA5mNiBfPxrj0Sohbnkf0kr162zmLAGpRlyfZrEaM3KmFHZmTwEwaQPBFGtTFbTjHvK/qaTgL+MO7JWvW/qM8uc88LCtFwZxE6IxVUcWN8yms0fW