name: Deploy Heroku

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8 pytest mongomock
          
      - name: Run test
        run: make test
        
  deploy:
    runs-on: ubuntu-22.04
    needs: test
    
    steps:
      - uses: actions/checkout@v4
      - name: deploy to heroku
        run: make heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
